#!/usr/bin/env python3
"""Build rerank_eligible_readings.json + C++ .inc (NEXT_TASK_USAGE_GUARD).

Source of truth: data/rerank_ctx/context_sensitive_map.json, which was built by
tools/rerank/build_ctx_dataset.py::build_context_sensitive_map from the attached
pool (top_gold_share<0.7, >=2 kanji golds gold!=reading freq>=3, content POS,
total>=8). reading_gold_map.json lacks POS, so it is recorded as a cross-check
only.

Seed readings: IME homophones missing from Wikipedia CS (きしゃ = 記者/汽車).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from tools.rerank.context_clip import has_kanji

ROOT = Path(__file__).resolve().parents[2]
CS_MAP = ROOT / "data/rerank_ctx/context_sensitive_map.json"
GOLD_MAP = ROOT / "data/rerank_ctx/reading_gold_map.json"
OUT_JSON = ROOT / "artifacts/rerank/rerank_eligible_readings.json"
OUT_INC = ROOT / "mozc_compat/rerank_eligible_readings.inc"
WORKSPACE_JSON = OUT_JSON

# IME smoke homophone; absent from Wikipedia CS map.
SEED_READINGS = ["きしゃ"]

# Usage-log hole-fill: Wikipedia CS, but Mozc-default is the right IME call
# (協会 vs 教会). After whitelist+heuristics this was the only remaining
# hurt pair; dropping it is what makes usage net ≥ 0.
BLOCKED_READINGS = ["きょうかい"]


def cs_from_gold_map(path: Path) -> set[str]:
    """Numeric CS criteria on reading_gold_map (no POS filter)."""
    if not path.is_file():
        return set()
    blob = json.loads(path.read_text(encoding="utf-8"))
    amb = blob.get("ambiguous") or {}
    out: set[str] = set()
    for reading, info in amb.items():
        golds = info.get("golds") or {}
        total = sum(int(n) for n in golds.values())
        if total < 8:
            continue
        top_n = max(int(n) for n in golds.values())
        if top_n / total >= 0.70:
            continue
        kanji_golds = [
            g
            for g, n in golds.items()
            if has_kanji(g) and g != reading and int(n) >= 3
        ]
        if len(kanji_golds) < 2:
            continue
        out.add(reading)
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cs-map", type=Path, default=CS_MAP)
    parser.add_argument("--gold-map", type=Path, default=GOLD_MAP)
    parser.add_argument("--out-json", type=Path, default=OUT_JSON)
    parser.add_argument("--out-inc", type=Path, default=OUT_INC)
    args = parser.parse_args()

    cs_blob = json.loads(args.cs_map.read_text(encoding="utf-8"))
    cs = set((cs_blob.get("context_sensitive") or {}).keys())
    gold_cs = cs_from_gold_map(args.gold_map)
    seeds = [s for s in SEED_READINGS if s not in cs]
    blocked = [s for s in BLOCKED_READINGS if s in cs or s in seeds]
    readings = sorted((cs | set(seeds)) - set(BLOCKED_READINGS))

    payload = {
        "source": str(args.cs_map.as_posix()),
        "criteria": (
            "top_gold_share<0.7 AND >=2 kanji golds (gold!=reading, freq>=3) "
            "AND content POS; total>=8 (build_context_sensitive_map)"
        ),
        "n_context_sensitive": len(cs),
        "n_gold_map_numeric_cs": len(gold_cs),
        "n_gold_map_not_in_cs": len(gold_cs - cs),
        "seed_readings": seeds,
        "blocked_readings": blocked,
        "n_eligible": len(readings),
        "readings": readings,
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    WORKSPACE_JSON.parent.mkdir(parents=True, exist_ok=True)
    WORKSPACE_JSON.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    lines = [
        "// Generated by tools/rerank/build_eligible_readings.py. Do not edit.",
        "// Sorted UTF-8 readings for binary search (NEXT_TASK_USAGE_GUARD).",
        "static constexpr const char* kEligibleReadings[] = {",
    ]
    for r in readings:
        if '"' in r or "\\" in r:
            raise SystemExit(f"unescapable reading: {r!r}")
        lines.append(f'    "{r}",')
    lines.append("};")
    lines.append(f"static constexpr size_t kEligibleReadingsSize = {len(readings)};")
    lines.append("")
    args.out_inc.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({k: payload[k] for k in (
        "n_context_sensitive",
        "n_gold_map_numeric_cs",
        "n_gold_map_not_in_cs",
        "seed_readings",
        "blocked_readings",
        "n_eligible",
    )}, ensure_ascii=False, indent=2))
    print("WROTE", args.out_json)
    print("WROTE", WORKSPACE_JSON)
    print("WROTE", args.out_inc)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
